-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value jsonb NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.artisan_lead_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  profile_id uuid,
  countries_served jsonb NOT NULL DEFAULT '{}'::jsonb,
  regions_served jsonb NOT NULL DEFAULT '{}'::jsonb,
  work_categories jsonb NOT NULL DEFAULT '{}'::jsonb,
  other_work_category text,
  receive_leads boolean DEFAULT false,
  max_leads_per_day integer DEFAULT 10,
  min_lead_value numeric,
  max_lead_value numeric,
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT artisan_lead_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT artisan_lead_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT artisan_lead_preferences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.blogs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  excerpt text,
  content text NOT NULL,
  featured_image text,
  category text DEFAULT 'general'::text CHECK (category = ANY (ARRAY['technology'::text, 'business'::text, 'tutorials'::text, 'news'::text, 'general'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  author_id uuid,
  published_at timestamp with time zone,
  meta_title text,
  meta_description text,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  language character varying DEFAULT 'en'::character varying CHECK (language::text = ANY (ARRAY['en'::character varying, 'fr'::character varying, 'nl'::character varying]::text[])),
  CONSTRAINT blogs_pkey PRIMARY KEY (id),
  CONSTRAINT blogs_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  country character varying,
  postal_code character varying,
  client_type character varying DEFAULT 'individual'::character varying,
  contact_person character varying,
  company_size character varying,
  vat_number character varying,
  peppol_id character varying,
  peppol_enabled boolean DEFAULT false,
  communication_preferences jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  language_preference character varying NOT NULL DEFAULT 'fr'::character varying,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.company_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  profile_id uuid,
  company_name character varying NOT NULL,
  logo_path character varying,
  logo_filename character varying,
  logo_size integer,
  logo_mime_type character varying,
  signature_path character varying,
  signature_filename character varying,
  signature_size integer,
  signature_mime_type character varying,
  address text,
  city character varying,
  state character varying,
  country character varying,
  postal_code character varying,
  phone character varying,
  email character varying,
  website character varying,
  vat_number character varying,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  iban character varying,
  account_name character varying,
  bank_name character varying,
  CONSTRAINT company_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT company_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT company_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.credit_insurance_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name character varying NOT NULL,
  contact_person character varying NOT NULL,
  email character varying NOT NULL,
  telephone character varying NOT NULL,
  address text NOT NULL,
  sector character varying NOT NULL,
  activity_description text NOT NULL,
  annual_turnover numeric NOT NULL,
  top_customers text NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'processing'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_insurance_applications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_outbox (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid,
  user_id uuid,
  follow_up_id uuid,
  to_email character varying NOT NULL,
  subject text NOT NULL,
  html text,
  text text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sending'::character varying, 'sent'::character varying, 'failed'::character varying]::text[])),
  email_type character varying,
  attempts integer DEFAULT 0,
  sent_at timestamp with time zone,
  last_error text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invoice_id uuid,
  CONSTRAINT email_outbox_pkey PRIMARY KEY (id),
  CONSTRAINT email_outbox_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT email_outbox_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT email_outbox_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.email_template_variables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  variable_name character varying NOT NULL UNIQUE,
  description text,
  example_value text,
  is_required boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_template_variables_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  template_type character varying NOT NULL,
  template_name character varying NOT NULL,
  subject text NOT NULL,
  html_content text NOT NULL,
  text_content text NOT NULL,
  variables jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  language character varying DEFAULT 'fr'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_verification_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  otp text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_verification_otps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.expense_invoices (
  id integer NOT NULL DEFAULT nextval('expense_invoices_id_seq'::regclass),
  invoice_number character varying NOT NULL UNIQUE,
  supplier_name character varying NOT NULL,
  supplier_email character varying,
  supplier_vat_number character varying,
  amount numeric NOT NULL,
  net_amount numeric,
  vat_amount numeric,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'paid'::character varying::text, 'overdue'::character varying::text, 'cancelled'::character varying::text])),
  category text,
  source character varying DEFAULT 'manual'::character varying CHECK (source::text = ANY (ARRAY['manual'::character varying, 'peppol'::character varying]::text[])),
  issue_date date NOT NULL,
  due_date date NOT NULL,
  payment_method character varying,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  peppol_enabled boolean DEFAULT false,
  peppol_message_id character varying,
  peppol_received_at timestamp without time zone,
  ubl_xml text,
  sender_peppol_id character varying,
  peppol_metadata jsonb DEFAULT '{}'::jsonb,
  user_id uuid,
  invoice_type character varying DEFAULT 'final'::character varying CHECK (invoice_type::text = ANY (ARRAY['deposit'::character varying, 'final'::character varying]::text[])),
  CONSTRAINT expense_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT expense_invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  user_id uuid NOT NULL,
  type character varying NOT NULL,
  meta jsonb DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT invoice_events_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_events_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.invoice_follow_ups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  user_id uuid NOT NULL,
  client_id uuid,
  stage smallint NOT NULL DEFAULT 1,
  scheduled_at timestamp with time zone NOT NULL,
  next_attempt_at timestamp with time zone,
  attempts smallint NOT NULL DEFAULT 0,
  max_attempts smallint NOT NULL DEFAULT 3,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  channel character varying NOT NULL DEFAULT 'email'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  automated boolean NOT NULL DEFAULT true,
  template_subject text,
  template_text text,
  template_html text,
  meta jsonb DEFAULT '{}'::jsonb,
  template_id uuid,
  template_variables jsonb DEFAULT '{}'::jsonb,
  last_error text,
  last_attempt timestamp with time zone,
  CONSTRAINT invoice_follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_follow_ups_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_follow_ups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT invoice_follow_ups_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT invoice_follow_ups_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.email_templates(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id uuid,
  quote_id uuid,
  invoice_number character varying NOT NULL,
  quote_number character varying,
  title text,
  description text,
  status character varying DEFAULT 'unpaid'::character varying CHECK (status::text = ANY (ARRAY['unpaid'::character varying, 'paid'::character varying, 'overdue'::character varying, 'cancelled'::character varying]::text[])),
  amount numeric NOT NULL,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  final_amount numeric NOT NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date NOT NULL,
  payment_method character varying,
  payment_terms text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  converted_from_quote_at timestamp with time zone DEFAULT now(),
  net_amount numeric DEFAULT 0,
  peppol_enabled boolean DEFAULT false,
  peppol_message_id character varying,
  peppol_status character varying DEFAULT 'not_sent'::character varying CHECK (peppol_status::text = ANY (ARRAY['not_sent'::character varying, 'sending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'failed'::character varying]::text[])),
  peppol_sent_at timestamp with time zone,
  peppol_delivered_at timestamp with time zone,
  peppol_error_message text,
  ubl_xml text,
  receiver_peppol_id character varying,
  peppol_metadata jsonb DEFAULT '{}'::jsonb,
  invoice_type character varying DEFAULT 'final'::character varying CHECK (invoice_type::text = ANY (ARRAY['deposit'::character varying, 'final'::character varying]::text[])),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT invoices_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT invoices_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.lead_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  artisan_user_id uuid NOT NULL,
  artisan_profile_id uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'assigned'::character varying,
  quote_id uuid,
  quote_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT lead_assignments_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.lead_requests(id),
  CONSTRAINT lead_assignments_artisan_user_id_fkey FOREIGN KEY (artisan_user_id) REFERENCES public.users(id),
  CONSTRAINT lead_assignments_artisan_profile_id_fkey FOREIGN KEY (artisan_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT lead_assignments_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.lead_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  artisan_user_id uuid NOT NULL,
  type character varying NOT NULL,
  channel character varying DEFAULT 'email'::character varying,
  subject text,
  message text,
  status character varying DEFAULT 'pending'::character varying,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT lead_notifications_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.lead_requests(id),
  CONSTRAINT lead_notifications_artisan_user_id_fkey FOREIGN KEY (artisan_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lead_quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  artisan_user_id uuid NOT NULL,
  artisan_profile_id uuid,
  quote_id uuid,
  quote_amount numeric,
  quote_currency character varying DEFAULT 'EUR'::character varying,
  status character varying DEFAULT 'sent'::character varying,
  viewed_at timestamp with time zone,
  responded_at timestamp with time zone,
  client_response text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_quotes_pkey PRIMARY KEY (id),
  CONSTRAINT lead_quotes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.lead_requests(id),
  CONSTRAINT lead_quotes_artisan_user_id_fkey FOREIGN KEY (artisan_user_id) REFERENCES public.users(id),
  CONSTRAINT lead_quotes_artisan_profile_id_fkey FOREIGN KEY (artisan_profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT lead_quotes_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.lead_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_categories ARRAY NOT NULL DEFAULT '{}'::text[],
  custom_category text,
  project_description text NOT NULL,
  price_range character varying,
  completion_date date,
  country character varying NOT NULL DEFAULT 'BE'::character varying,
  region character varying NOT NULL,
  street_number character varying,
  full_address text NOT NULL,
  city character varying DEFAULT 'N/A'::character varying,
  zip_code character varying NOT NULL,
  client_name character varying NOT NULL,
  client_email character varying NOT NULL,
  client_phone character varying NOT NULL,
  client_address text NOT NULL,
  communication_preferences jsonb DEFAULT '{"sms": false, "email": true, "phone": false}'::jsonb,
  project_images ARRAY DEFAULT '{}'::text[],
  status character varying DEFAULT 'active'::character varying,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_spam boolean DEFAULT false,
  spam_reason text,
  reported_by_user_id uuid,
  reported_at timestamp with time zone,
  spam_reviewed_by uuid,
  spam_reviewed_at timestamp with time zone,
  spam_review_status character varying DEFAULT 'pending'::character varying,
  CONSTRAINT lead_requests_pkey PRIMARY KEY (id),
  CONSTRAINT lead_requests_reported_by_user_id_fkey FOREIGN KEY (reported_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lead_requests_spam_reviewed_by_fkey FOREIGN KEY (spam_reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.lead_spam_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL,
  reported_by_user_id uuid NOT NULL,
  reason text NOT NULL,
  report_type character varying DEFAULT 'spam'::character varying,
  additional_details text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_status character varying DEFAULT 'pending'::character varying,
  review_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lead_spam_reports_pkey PRIMARY KEY (id),
  CONSTRAINT lead_spam_reports_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.lead_requests(id),
  CONSTRAINT lead_spam_reports_reported_by_user_id_fkey FOREIGN KEY (reported_by_user_id) REFERENCES public.users(id),
  CONSTRAINT lead_spam_reports_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.payment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  user_id uuid NOT NULL,
  stripe_payment_intent_id character varying UNIQUE,
  stripe_invoice_id character varying,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'EUR'::character varying,
  status character varying NOT NULL,
  payment_method character varying,
  description text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT payment_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.peppol_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  invoice_number character varying NOT NULL,
  document_type character varying NOT NULL DEFAULT 'INVOICE'::character varying,
  reference_number character varying,
  direction character varying NOT NULL CHECK (direction::text = ANY (ARRAY['outbound'::character varying, 'inbound'::character varying]::text[])),
  sender_id uuid,
  sender_peppol_id character varying,
  sender_name character varying,
  sender_vat_number character varying,
  sender_email character varying,
  receiver_peppol_id character varying,
  receiver_name character varying,
  receiver_vat_number character varying,
  receiver_email character varying,
  issue_date date NOT NULL,
  due_date date,
  delivery_date date,
  payment_terms text,
  buyer_reference character varying,
  currency character varying DEFAULT 'EUR'::character varying,
  subtotal_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  ubl_xml text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'delivered'::character varying, 'received'::character varying, 'processed'::character varying, 'failed'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  peppol_message_id character varying,
  retry_count integer DEFAULT 0,
  sent_at timestamp with time zone,
  received_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  client_invoice_id uuid,
  supplier_invoice_id integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT peppol_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT peppol_invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT peppol_invoices_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.peppol_participants(id),
  CONSTRAINT peppol_invoices_client_invoice_id_fkey FOREIGN KEY (client_invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT peppol_invoices_supplier_invoice_id_fkey FOREIGN KEY (supplier_invoice_id) REFERENCES public.expense_invoices(id)
);
CREATE TABLE public.peppol_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  peppol_identifier character varying NOT NULL,
  business_name character varying NOT NULL,
  vat_number character varying,
  country_code character varying NOT NULL,
  contact_name character varying,
  contact_email character varying,
  contact_phone character varying,
  street_address text,
  city character varying,
  zip_code character varying,
  country character varying,
  supported_document_types ARRAY DEFAULT ARRAY[]::text[],
  is_registered boolean DEFAULT false,
  is_active boolean DEFAULT true,
  last_verified timestamp with time zone,
  verification_status character varying DEFAULT 'pending'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT peppol_participants_pkey PRIMARY KEY (id),
  CONSTRAINT peppol_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.peppol_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  peppol_id character varying NOT NULL UNIQUE,
  business_name character varying NOT NULL,
  country_code character varying NOT NULL DEFAULT 'BE'::character varying,
  contact_person_name character varying,
  contact_person_email character varying,
  contact_person_phone character varying,
  contact_person_language character varying DEFAULT 'en-US'::character varying,
  supported_document_types ARRAY DEFAULT ARRAY['INVOICE'::text, 'CREDIT_NOTE'::text],
  limited_to_outbound_traffic boolean DEFAULT false,
  sandbox_mode boolean DEFAULT true,
  is_configured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  last_tested timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  peppol_disabled boolean DEFAULT false,
  peppol_id_9925 character varying,
  peppol_id_0208 character varying,
  CONSTRAINT peppol_settings_pkey PRIMARY KEY (id),
  CONSTRAINT peppol_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.predefined_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  category character varying,
  name character varying NOT NULL,
  description text,
  default_unit character varying,
  default_price numeric,
  icon_name character varying,
  is_active boolean DEFAULT true,
  is_global boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT predefined_materials_pkey PRIMARY KEY (id),
  CONSTRAINT predefined_materials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.predefined_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  category character varying,
  title character varying NOT NULL,
  description text,
  default_duration numeric,
  default_price numeric,
  icon_name character varying,
  is_active boolean DEFAULT true,
  is_global boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT predefined_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT predefined_tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.quote_access_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  share_token character varying,
  action character varying,
  accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT quote_access_logs_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quote_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  profile_id uuid,
  draft_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_saved timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  quote_number character varying,
  CONSTRAINT quote_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT quote_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT quote_drafts_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.quote_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  user_id uuid,
  type character varying NOT NULL,
  meta jsonb DEFAULT '{}'::jsonb,
  timestamp timestamp with time zone DEFAULT now(),
  share_token character varying,
  CONSTRAINT quote_events_pkey PRIMARY KEY (id),
  CONSTRAINT quote_events_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.quote_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  file_name character varying NOT NULL,
  file_path character varying NOT NULL,
  file_size integer,
  mime_type character varying,
  file_category character varying,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_files_pkey PRIMARY KEY (id),
  CONSTRAINT quote_files_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.quote_financial_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  vat_config jsonb DEFAULT '{}'::jsonb,
  advance_config jsonb DEFAULT '{}'::jsonb,
  marketing_banner jsonb DEFAULT '{}'::jsonb,
  payment_terms jsonb DEFAULT '{}'::jsonb,
  discount_config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  show_material_prices boolean DEFAULT false,
  CONSTRAINT quote_financial_configs_pkey PRIMARY KEY (id),
  CONSTRAINT quote_financial_configs_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quote_follow_ups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  user_id uuid NOT NULL,
  client_id uuid,
  stage smallint NOT NULL,
  scheduled_at timestamp with time zone NOT NULL,
  next_attempt_at timestamp with time zone,
  attempts smallint NOT NULL DEFAULT 0,
  max_attempts smallint NOT NULL DEFAULT 3,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  channel character varying NOT NULL DEFAULT 'email'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  automated boolean NOT NULL DEFAULT true,
  template_subject text,
  template_text text,
  template_html text,
  meta jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT quote_follow_ups_pkey PRIMARY KEY (id),
  CONSTRAINT quote_follow_ups_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_follow_ups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT quote_follow_ups_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.quote_materials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  quote_task_id uuid,
  name character varying NOT NULL,
  description text,
  quantity numeric DEFAULT 1,
  unit character varying DEFAULT 'piece'::character varying,
  unit_price numeric DEFAULT 0,
  total_price numeric DEFAULT 0,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_materials_pkey PRIMARY KEY (id),
  CONSTRAINT quote_materials_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT quote_materials_quote_task_id_fkey FOREIGN KEY (quote_task_id) REFERENCES public.quote_tasks(id)
);
CREATE TABLE public.quote_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  share_token character varying NOT NULL UNIQUE,
  access_count integer DEFAULT 0,
  last_accessed timestamp with time zone,
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_shares_pkey PRIMARY KEY (id),
  CONSTRAINT quote_shares_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quote_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  signer_name character varying NOT NULL,
  signer_email character varying,
  signature_data text,
  signature_mode character varying DEFAULT 'draw'::character varying,
  signature_type character varying DEFAULT 'client'::character varying,
  signature_file_path character varying,
  signature_filename character varying,
  signature_size integer,
  signature_mime_type character varying,
  customer_comment text,
  signed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT quote_signatures_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quote_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quote_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  quantity numeric DEFAULT 1,
  unit character varying DEFAULT 'piece'::character varying,
  unit_price numeric DEFAULT 0,
  total_price numeric DEFAULT 0,
  duration numeric,
  duration_unit character varying DEFAULT 'minutes'::character varying,
  pricing_type character varying DEFAULT 'flat'::character varying,
  hourly_rate numeric,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quote_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT quote_tasks_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  profile_id uuid,
  company_profile_id uuid,
  client_id uuid,
  quote_number character varying NOT NULL,
  title text,
  description text,
  status character varying DEFAULT 'draft'::character varying,
  project_categories ARRAY DEFAULT '{}'::text[],
  custom_category text,
  total_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  final_amount numeric DEFAULT 0,
  valid_until date,
  terms_conditions text,
  share_token character varying UNIQUE,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  start_date date,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  sent_at timestamp with time zone,
  rejection_reason text,
  view_only_token character varying UNIQUE,
  deposit_amount numeric DEFAULT 0,
  balance_amount numeric DEFAULT 0,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT quotes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.user_profiles(id),
  CONSTRAINT quotes_company_profile_id_fkey FOREIGN KEY (company_profile_id) REFERENCES public.company_profiles(id),
  CONSTRAINT quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.subscription_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  notification_type character varying NOT NULL,
  subscription_data jsonb,
  email_sent boolean DEFAULT false,
  email_error text,
  sent_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_subscription_id character varying UNIQUE,
  stripe_customer_id character varying,
  plan_name character varying NOT NULL,
  plan_type character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'trialing'::character varying,
  interval character varying NOT NULL DEFAULT 'monthly'::character varying,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'EUR'::character varying,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  email text,
  role text NOT NULL,
  avatar text,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  pin text,
  is_active boolean DEFAULT false,
  last_active timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  company_name text,
  phone text,
  profession text,
  country text DEFAULT 'FR'::text,
  business_size text,
  selected_plan text DEFAULT 'pro'::text,
  subscription_status text DEFAULT 'trial'::text,
  stripe_customer_id text,
  stripe_subscription_id text,
  trial_start_date timestamp with time zone,
  trial_end_date timestamp with time zone,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  vat_number text,
  role text DEFAULT 'admin'::text CHECK (role = ANY (ARRAY['admin'::text, 'superadmin'::text])),
  last_login_at timestamp with time zone,
  registration_completed boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  email_verified_at timestamp with time zone,
  analytics_objectives jsonb DEFAULT '{"clientTarget": null, "revenueTarget": null, "projectsTarget": null}'::jsonb,
  language_preference character varying NOT NULL DEFAULT 'fr'::character varying,
  first_name text,
  last_name text,
  has_used_trial boolean DEFAULT false,
  has_lifetime_access boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);



-------